SharedLibrary: silence error in function pointer case in LLVM
base/system/tsSharedLibrary.cpp:122:18: error: assigning to 'void *' from 'FARPROC' (aka 'long long (*)()') converts between void pointer and function pointer

static_cast doesn't work so we use a C-style cast.
The getSymbol() method is not used anyway.