msvc-common-base.props:  Add /bigobj for release builds to allow tsduck.cpp to build with VS2015
While the /bigobj compilation option had already been added for debug builds, it is also needed for release builds, at least on VS2015, when building tsduck.cpp.  Without this option, tsduck.cpp fails to build due to compilation error C1128.